"""creating new event cols

Revision ID: b713623ac198
Revises: a98436f1b626
Create Date: 2023-07-12 14:44:33.932596

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b713623ac198'
down_revision = 'a98436f1b626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='statusenum'), nullable=True))
    op.add_column('event', sa.Column('location_city', sa.String(), nullable=True))
    op.add_column('event', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('location_lon', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('location_name', sa.String(), nullable=True))
    op.add_column('event', sa.Column('location_street', sa.String(), nullable=True))
    op.add_column('event', sa.Column('location_zipcode', sa.String(), nullable=True))
    op.add_column('event', sa.Column('categories', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('event', sa.Column('poster_medium', sa.String(), nullable=True))
    op.add_column('event', sa.Column('poster_small', sa.String(), nullable=True))
    op.add_column('event', sa.Column('external_ticket_id', sa.Integer(), nullable=True))
    op.alter_column('event', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'ticket_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'ticket_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('event', 'external_ticket_id')
    op.drop_column('event', 'poster_small')
    op.drop_column('event', 'poster_medium')
    op.drop_column('event', 'categories')
    op.drop_column('event', 'location_zipcode')
    op.drop_column('event', 'location_street')
    op.drop_column('event', 'location_name')
    op.drop_column('event', 'location_lon')
    op.drop_column('event', 'location_lat')
    op.drop_column('event', 'location_city')
    op.drop_column('event', 'status')
    # ### end Alembic commands ###
